source 'https://rubygems.org'

gem 'capybara' # Released: January 24, 2019
gem 'rexml'
gem 'rspec'# Released: August 4, 2018
gem 'selenium-webdriver'# Released: November 1, 2018
gem 'launchy'# Released November 3, 2014
gem 'ffi'
