source 'https://rubygems.org'

gem 'capybara', '~> 3.13', '>= 3.13.2' # Released: January 24, 2019
gem 'rspec', '~> 3.8' # Released: August 4, 2018
gem 'selenium-webdriver', '~> 3.141' # Released: November 1, 2018
gem 'launchy', '~> 2.4', '>= 2.4.3' # Released November 3, 2014
