source 'https://rubygems.org'

gem 'capybara', '~> 3.32', '>= 3.32.2' # Released: May 16, 2020
gem 'rspec', '~> 3.9' # Released: October 08, 2019
gem 'rubocop', '~> 0.84.0' # Released: May 21, 2020
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.7' # Released: December 27, 2019
gem 'launchy', '~> 2.5' # Released February 28, 2020
gem 'webdrivers', '~> 4.3' # Released April 15, 2020
gem 'ffi', '~> 1.12', '>= 1.12.2' # Released February 01, 2020
