source 'https://rubygems.org'

gem 'capybara', '~> 3.39', '>= 3.39.2' # June 10, 2023
gem 'rspec', '~> 3.12' # October 26, 2022
gem 'apparition', '~> 0.6.0', github: 'twalpole/apparition'
gem 'selenium-webdriver', '~> 4.13', '>= 4.13.1' # September 26, 2023
gem 'ffi', '~> 1.16', '>= 1.16.2' # September 25, 2023
gem 'rexml', '~> 3.2', '>= 3.2.6' # July 27, 2023
